### ISSUE TITLE
Is there a tool to use OPAL

### ISSUE THREAD

**Issue by BabaYB** [smx-smx/ASMTool#1]
I have a SSD which connected to PC by USB via ASMedia.
And I wanna use the encryption to protect my data in the ssd, but I have no idea how to use OPAL at now.
I have tried sedutil but `sedutil --scan` says there is no OPAL compliant device.
BTW my SSD is samsung EVO 970.

Thanks,
Baba_YB

**Comment by smx-smx** [comment]
Sorry for the late reply, but there's not much that can be done about it
This tool taps in the interface to the chip, it doesn't do much with the actual firmware and it can't do much because there is no public datasheet about the controller either
