### ISSUE TITLE
Windows binary of ASMTool

### ISSUE THREAD

**Issue by t0niX** [smx-smx/ASMTool#6]
Hi smx,

thanks for your repo! 

As I mistakenly flashed a wrong firmware to my ASM 3074 (I used one for an ASM 3142 as I thought that’s the chip on my motherboard; It still works though) I would like to re-flash the original firmware. Sadly it’s not available publicly

The good thing is: My motherboard has two ASM 3074 controllers of which one was deactivated during the flash so it still has the original firmware on it. This is the one I would like to dump the firmware from.

I am not a coder which is why I don’t have any tools to build myself a binary of your repo. Would you be so kind to compile a version for windows for me and share it? Can I re-flash the extracted firmware 1:1 or do I need to edit the file using a hex editor?

Thank you!!

**Comment by smx-smx** [comment]
I configured CirrusCI to build and upload the artifacts.
You can find them here: https://cirrus-ci.com/github/smx-smx/ASMTool/master

Click on the latest build, then navigate to `binaries/build` and download the zip file.
For usage, refer to the README

![screenshot](https://github.com/smx-smx/ASMTool/assets/1978844/c1eadd19-4cf5-47fb-b169-3bcd06d0fbd5)

**Comment by necros2k7** [comment]
win11:
AsmTool.exe
Unloading ASM Driver...
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'asmiodll'
 (0x8007007E)
   at AsmTool.AsmIODll.UnloadAsmIODriver()
   at AsmTool.WindowsAsmIO.UnloadAsmIODriver() in C:\Users\ContainerAdministrato
Tool\WindowsAsmIO.cs:line 99
   at AsmTool.Program.Main(String[] args) in C:\Users\ContainerAdministrator\App
Program.cs:line 24

**Comment by t0niX** [comment]
Thanks a lot!

**Comment by t0niX** [comment]
> win11:
> AsmTool.exe
> Unloading ASM Driver...
> Unhandled exception. System.DllNotFoundException: Unable to load DLL 'asmiodll'
> (0x8007007E)
> at AsmTool.AsmIODll.UnloadAsmIODriver()
> at AsmTool.WindowsAsmIO.UnloadAsmIODriver() in C:\Users\ContainerAdministrato
> Tool\WindowsAsmIO.cs:line 99
> at AsmTool.Program.Main(String[] args) in C:\Users\ContainerAdministrator\App
> Program.cs:line 24

You need to add the .dlls mentioned in the ReadMe to the same folder!

**Comment by smx-smx** [comment]
It would be a good idea to collect those firmwares, for people that don't have dual/redundant controllers (me for example, i'm still looking for ASM2142 firmwares).
I created a topic in Github Discussions where you can upload firmware dumps

**Comment by necros2k7** [comment]
Unloading ASM Driver...
Unhandled exception. System.BadImageFormatException: Attempt was made to load
(0x8007000B)
   at AsmTool.AsmIODll.UnloadAsmIODriver()
   at AsmTool.WindowsAsmIO.UnloadAsmIODriver() in C:\Users\ContainerAdministrato
Tool\WindowsAsmIO.cs:line 99
   at AsmTool.Program.Main(String[] args) in C:\Users\ContainerAdministrator\App
Program.cs:line 24

**Comment by necros2k7** [comment]
Can`t find asmiodll.dll x64 - anyone have a link?

**Comment by smx-smx** [comment]
Yes it should be x86. You can get the files from here: https://www.inateck.com/blogs/news/asm3142-firmware-upgrade-operation-steps

Copy all .dll and .sys files

**Comment by necros2k7** [comment]
copied but still:
Unloading ASM Driver...
Unhandled exception. System.BadImageFormatException: Attempt was made to load
(0x8007000B)
   at AsmTool.AsmIODll.UnloadAsmIODriver()
   at AsmTool.WindowsAsmIO.UnloadAsmIODriver() in C:\Users\ContainerAdministrato
Tool\WindowsAsmIO.cs:line 99
   at AsmTool.Program.Main(String[] args) in C:\Users\ContainerAdministrator\App
Program.cs:line 24

**Comment by t0niX** [comment]
ASMTool needs to be compiled in x86/32 bit. Then it will work.

**Comment by necros2k7** [comment]
> ASMTool needs to be compiled in x86/32 bit. Then it should work.

Then why author compiles in x64? https://cirrus-ci.com/github/smx-smx/ASMTool/master

**Comment by smx-smx** [comment]
That's a mistake, thanks for reporting. The CI runner is x64 (which is why i called the jobs _x64), but i forgot to specify the x86 target.
I will fix it this evening and rename the job accordingly

**Comment by smx-smx** [comment]
It should be fixed by 4d70d0da35eff91884a40708453bfb54d7a90daf. Can you verify?

**Comment by necros2k7** [comment]
It`s ok now, thanx!
